import commands, os
from subprocess import Popen, PIPE
from glob import glob

Import("*")

#
# Source lists
#

wesnoth_sources = Split("""
	wml_parser.cpp
""")

libwesnoth_extras = client_env.Library("wesnoth_extras", wesnoth_sources)



json_parser_sources = Split("""
	parser.cpp
""")

libjson_extras = client_env.Library("json_extras", json_parser_sources)



kernel_sources = Split("""
	kernel/kernel.cpp
	kernel/kernel_types.cpp
	kernel/game_data.cpp
	kernel/lua_common.cpp
	kernel/lua_rng.cpp
	kernel/mt_rng.cpp
	kernel/seed_rng.cpp
	string_utils.cpp
""")

libkernel_extras = client_env.Library("kernel_extras", kernel_sources)

#
# Target declarations
#

def error_action(target, source, env):
    from SCons.Errors import UserError
    raise UserError, "Target disabled because its prerequisites are not met"

def WesnothProgram(env, target, source, can_build, **kw):
    bin = env.Program("#/" + target + build_suffix, source, **kw)
    env.Alias(target, bin)
    locals()[target] = bin
    Export(target)

client_env.AddMethod(WesnothProgram)

#
# wml (parser) binary
#

wml_objects = ["wml.cpp", libwesnoth_extras]

bin = env.Program("#/wml", wml_objects)
env.Alias("wml", bin)

#
# attr binary
#

attr_objects = ["attr.cpp", libwesnoth_extras]

bin = env.Program("#/attr", attr_objects)
env.Alias("attr", bin)

#
# json binary
#

json_objects = ["json_parser.cpp", libjson_extras]

bin = env.Program("#/json", json_objects)
env.Alias("json", bin)

#
# kv binary
#

bin = env.Program("#/kv", ["key_value_sequence.cpp"])
env.Alias("kv", bin)

#
# nl binary

bin = env.Program("#/nl", ["num_list.cpp"])
env.Alias("nl", bin)

#
# attr2 binary

attr2_objects = ["attr2.cpp", libwesnoth_extras]

bin = env.Program("#/attr2", attr2_objects)
env.Alias("attr2", bin)

#
# test binary

test_objects = ["test.cpp", libwesnoth_extras]
bin = env.Program("#/test", test_objects)
env.Alias("test", bin)

#
# test_kernel
#

kernel_objects = ["kernel_test.cpp", libkernel_extras]
eris = SConscript("eris/SConscript")
kernel_objects.extend(eris)

bin = env.Program("#/kernel_test", kernel_objects)
env.Alias("kernel_test", bin)
env.Alias("kernel", bin)

#Export("wesnoth")
